### ISSUE TITLE
Update to Node 16

### ISSUE THREAD

**Issue by neerup** [Reedyuk/read-properties#1]
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/4113036/196034914-8d1441eb-b7dd-4527-98a6-fdd91822cd49.png">

**Comment by Reedyuk** [comment]
If you want to put a pr in, happy to merge it

**Comment by Reedyuk** [comment]
Nevermind, just done it now. Please use version 1.0.2
