### ISSUE TITLE
Please update @actions/core to 1.10.0

### ISSUE THREAD

**Issue by neerup** [Reedyuk/read-properties#3]
Sorry to bother You again...
Could you update @actions/core to 1.10.0

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
<img width="1865" alt="image" src="https://user-images.githubusercontent.com/4113036/196323044-94c6dfaa-120b-4070-b7c3-9fda50900d62.png">

**Comment by Reedyuk** [comment]
hi @neerup can you try 1.0.3

**Comment by neerup** [comment]
> hi @neerup can you try 1.0.3

Sorry still getting warnings... Think @actions/core to 1.10.0 should be updated in [package-lock.json](https://github.com/Reedyuk/read-properties/blob/main/package-lock.json) aswell
